### ISSUE TITLE
Editor :: Frames reorder randomly when there are more than 10 frames

### ISSUE THREAD

**Issue by lfbrandao** [Zeega/Zeega#1218]
Created new project
Added a frame; made one layer persistent
Added layers to the frames, etc

Added new frames ---> the order of the frames that I previously created changes

**Comment by ahmedmkabil** [comment]
Have had two users in the past couple of days report this bug. Makes editing an incredibly frustrating experience, as any time one adds a frame the order of the frames gets randomized. It'd be great if we could have this fixed before Tribeca users start experimenting with Zeega in advance of workshop.

**Comment by jshapins** [comment]
We need to identify what exactly is causing this issue.

**Comment by ahmedmkabil** [comment]
Figured it out. Anytime a frame is added after the 10th frame, it triggers the reordering bug.
