### ISSUE TITLE
Bookmarklet :: YouTube playlist ingestion errors

### ISSUE THREAD

**Issue by jshapins** [Zeega/Zeega#1220]
Items are added, but:
- In item viewer only thumb is displayed
- This tag is also added: http://gdata.youtube.com/schemas/2007#video
- And in playback, the Zeega logo is displayed for citations instead of the YouTube logo

**Comment by lfbrandao** [comment]
This should be a front-end issue:
- In item viewer only thumb is displayed
- And in playback, the Zeega logo is displayed for citations instead of the YouTube logo

**Comment by jshapins** [comment]
What's strange is that both item viewer and citations work for YT items ingested individually. Only off when ingested via playlist.
