### ISSUE TITLE
Editor :: Deleting continuous layer still buggy

### ISSUE THREAD

**Issue by jamesburns** [Zeega/Zeega#1276]

**Comment by jamesburns** [comment]
I think this occurs when a layer moves from existing on a couple of layers to continuing on sequence.

**Comment by jshapins** [comment]
I've confirmed the issue. 
- Continue a layer to next frame
- Change status and continue layer to sequence
- Delete layer
- Only deletes layer on the individual frame instead of the entire sequence (as is expected for a layer that continues to sequence)

**Comment by jshapins** [comment]
The above issues now appear resolved. However, there is still bugginess: 

After deleting a layer continued to the sequence, then adding a new frame, the layer deleted layer appears on that frame.
