### ISSUE TITLE
Link layer links to incorrect frame

### ISSUE THREAD

**Issue by ahmedmkabil** [Zeega/Zeega#1371]
Linking to new frame will always link to the initial generated frame, even if initial frame is moved around the sequence.

Screencast of issue here:
http://www.youtube.com/watch?v=1c0DfjM7BE8

Project example here:
http://alpha.zeega.org/editor/3997

**Comment by jshapins** [comment]
This is not a bug. This the appropriate behavior. But it points to the general issue that clarifying how links are related to specific frames and how to make it easier to change links is important. Also, separating creating a new sequence from linking will hopefully also improve this.
