### ISSUE TITLE
Re-appearing layers

### ISSUE THREAD

**Issue by jshapins** [Zeega/Zeega#1441]
Need to specify how to reproduce this, but bug appears consistently...

Add layers to one frame, then add another frame. Sometimes the layers of frame 1 re-appear on the added frame in the editor frame window but not the layers tab. Refresh fixes this.

**Comment by jamesburns** [comment]
Guessing that this is tied to the layer reordering issue – i.e. it is happening w/ "broken" layers

**Comment by jamesburns** [comment]
Removing high priority label as it may have been dealt with in latest updates.

**Comment by jshapins** [comment]
This has not reoccured. Closing for now.
