### ISSUE TITLE
Tags don't save when publishing a project

### ISSUE THREAD

**Issue by jshapins** [Zeega/Zeega#1451]

**Comment by jshapins** [comment]
See first three projects here: 

http://alpha.zeega.org/library#view_type=list&content=project&universe=1&

Each was tagged "makingof" when publishing but they currently don't have the tag

**Comment by lfbrandao** [comment]
The tags are being sent to the API as a string instead of an array, so they are ignored. I'm passing this to James since I'm not sure what's the best way of parsing the input of that textbox into an array.

**Comment by jamesburns** [comment]
tags now being sent as an array
