### ISSUE TITLE
No new items added to new collection

### ISSUE THREAD

**Issue by mollydesjardin** [Zeega/Zeega#1458]
From user khowell60@gmail.com:

I tried to add new information to my collection by dragging the search items.
Nothing is added to the new collection.

For my test collection making
I searched  北海道伊達市 excluding tweets
Then, 22 items appeared to the page.
Then, I dragged the first three items to a box saying new collection 943.
Then, I clicked Go to Collection
The result was the new collection 943 page did not contain the items I moved.

**Comment by jshapins** [comment]
I repeated these steps and verified the issue.

**Comment by nickkapur** [comment]
I have replicated this problem a few times with different users. The items eventually do show up, but it takes multiple page reloads/waiting before they do. This will definitely be confusing to users, and did not used to happen in the past.
