### ISSUE TITLE
Media Library :: Tagging an item (Project) that is not one's own breaks published version of project

### ISSUE THREAD

**Issue by jshapins** [Zeega/Zeega#1469]
Logged in as admin
Tagged a project made for the Making Of w/ makingof
(Sandi King: No Goodbye)
Project doesn't load: http://alpha.zeega.org/75748
Tag doesn't appear in item viewer, but it does appear on the page tied to makingof query: http://blogs.kqed.org/makingof/zeega-test-page/

**Comment by lfbrandao** [comment]
Was this done today? I believe this is something @jamesburns fixed a couple of days ago but I'm not sure if it made it to the production server. I tried this on staging and didn't run into any problems.

**Comment by lfbrandao** [comment]
@jshapins you have to publish the project again to fix it

**Comment by jshapins** [comment]
How can I publish the project again? Since the project doesn't load, I
can't click to the user page. Other ways?

**Comment by lfbrandao** [comment]
I fixed it - it's up again. James is looking at the tags issue

**Comment by jshapins** [comment]
A potential near-term solution to this that would also be helpful in other
ways would be to add the Zeega author info to the created by field in the
item viewer and make that a link to the user page.
