### ISSUE TITLE
Library :: Cannot drag Zeega items into collection

### ISSUE THREAD

**Issue by jshapins** [Zeega/Zeega#1515]
ERROR

Error getting active collection for collections drawer discovery.js:69
PUT http://zeega.com/api/items/73916/items 500 (Internal Server Error) require-jquery.js:10056
Object {readyState: 4, setRequestHeader: function, getAllResponseHeaders: function, getResponseHeader: function, overrideMimeType: function…}
 discovery.js:69

**Comment by lfbrandao** [comment]
It's working for me
