### ISSUE TITLE
Add loading indicator to frames

### ISSUE THREAD

**Issue by lfbrandao** [Zeega/Zeega#1524]
Got several black screens on http://zeega.com/88277 because the YouTube videos take a while to load and wasn't sure what was happening.

**Comment by lfbrandao** [comment]
Hey @jshapins - this has been happening to me frequently, even on fast connections. I find it a bit confusing when I'm playing a project and there's a black screen for 15-30sec while the media item is loading.

**Comment by jshapins** [comment]
Yup. Closed because we moved to player repo.
