### ISSUE TITLE
alpha1.zeega.org does not load database nor does it work to "Create new project"

### ISSUE THREAD

**Issue by jshapins** [Zeega/Zeega#208]
Login on alpha1.zeega.org still works and displays new interface. But database does not display (only spinner). And "Create new project" simply places a # after the URL. 

Can we redirect all from alpha1.zeega.org to alpha.zeega.org?

**Comment by jamesburns** [comment]
Alpha1 disabled.

**Comment by jshapins** [comment]
Did u make a change to resolve this? See my note re: not being redirected.

**Comment by jamesburns** [comment]
alpha1 is disabled!

On Tue, Nov 22, 2011 at 12:23 PM, jshapins <
reply@reply.github.com

> wrote:
> 
> Did u make a change to resolve this? See my note re: not being redirected.
>
