### ISSUE TITLE
Deleting many layers causes delays and may not actually work

### ISSUE THREAD

**Issue by jbergen** [Zeega/Zeega#211]
probably caused because each delete action calls for a node thumb update which clogs the pipes.

**Comment by metalabharvard** [comment]
This should be solved by the 5 second delay on thumb refresh no?

James

## 

James C Burns
metaLAB (at) Harvard http://metalab.harvard.edu/
Berkman Center for Internet & Society

On Tue, Nov 22, 2011 at 3:21 PM, Joseph Bergen <
reply@reply.github.com
