### ISSUE TITLE
Auto-advance after playback doesn't work in standalone player

### ISSUE THREAD

**Issue by jshapins** [Zeega/Zeega#237]
See: http://alpha.zeega.org/web/project/209/view

**Comment by jshapins** [comment]
I've now changed them all to auto-advance after 10 seconds (which works and is rad!). But the bug exists.

**Comment by jbergen** [comment]
this should work now. THe problem was that new nodes didn't have an auto-advance attribute.

**Comment by jshapins** [comment]
Nice!!! Did u watch my piece? Had SO much fun using Zeega to make this. Very exciting. 

Glad to hear bfast burritos awesome! It's super sunny here in Indiana - almost has light quality of Land of Enchantment. 

Happiest of holly days!

~jms

**Comment by jbergen** [comment]
That is some crazy footage. Is that yours from your recent trip? Very cool

On Sat, Dec 24, 2011 at 11:34 AM, jshapins <
reply@reply.github.com

> wrote:
> 
> Nice!!! Did u watch my piece? Had SO much fun using Zeega to make this.
> Very exciting.
> 
> Glad to hear bfast burritos awesome! It's super sunny here in Indiana -
> almost has light quality of Land of Enchantment.
> 
> Happiest of holly days!
> 
> ~jms
>

**Comment by jshapins** [comment]
Yup. Being in Tokyo started thinking about this Zeega project - all 10 sec short, still videos on my iPhone. Going to keep pursuing in other cities!
