### ISSUE TITLE
Collection Browser - new collection replaces newest collection

### ISSUE THREAD

**Issue by jamesburns** [Zeega/Zeega#307]
When you create a new collection, it replaces first collection in my collections tray.
Not a database issue, i.e. ok on refresh.

**Comment by kanarinka** [comment]
I'm not able to replicate this on my version or on staging.

**Comment by jamesburns** [comment]
Try deleting all of your collections and starting with just a couple.  Jesse originally detected and I'm able to recreate on staging.  Can send screen capture, if still not happening for you.
