### ISSUE TITLE
Collection Browser - tab switching issues

### ISSUE THREAD

**Issue by jamesburns** [Zeega/Zeega#310]
opened a collection, jumped to my stuff tab. instead of showing my stuff. showed me that collection still underneath my stuff tab   "doesn't consistently happen. will try to recreate. 
ok, appears to happen when you jump around alot. like from one tab to another tab to a new collection, back to a tab."

**Comment by kanarinka** [comment]
9b4d578967ad371ef7e09d693c9bc1ef81639435
