### ISSUE TITLE
check username and mediaowner to enable deleting items

### ISSUE THREAD

**Issue by LindseyWagner** [Zeega/Zeega#330]

**Comment by kanarinka** [comment]
I checked sessionStorage and I don't have any username or user_id set there. Let me know how to get that field and I will put it there. 

It looks like I need the id and I will check it against the field user_id which is stored on the item. Let me know if that's not correct.

**Comment by kanarinka** [comment]
4748eaee1ace9c459e212dc4de6a7b6a6d10bff4

i think i got it - need to double check on staging once there are more users to verify this works
