### ISSUE TITLE
Bookmarklet pointing to dev database not staging

### ISSUE THREAD

**Issue by LindseyWagner** [Zeega/Zeega#343]

**Comment by jshapins** [comment]
This got broken w/ dash update - super easy to fix - but our cell phone wireless making it hard for James to fix - might have to wait until we get to Columbia ca 1:30

**Comment by LindseyWagner** [comment]
luis said he's on it.

On Thu, Feb 2, 2012 at 12:07 PM, Jesse Shapins <
reply@reply.github.com

> wrote:
> 
> This got broken w/ dash update - super easy to fix - but our cell phone
> wireless making it hard for James to fix - might have to wait until we get
> to Columbia ca 1:30
>
