### ISSUE TITLE
Collection Browser - Fix Collection settings menu + modal

### ISSUE THREAD

**Issue by jamesburns** [Zeega/Zeega#351]
white hover text hard to read
replace gear w/ corner cut? need to have same as editor?
formatting of renaming collection needs work.
Remove share link
Remove word 'close'  don't need two options for close

**Comment by kanarinka** [comment]
changed back to corner cut for the moment. for me, it's less obtrusive than gear but see what you think. Fixed other things.
51a3cb2c4fd87bed3f2c8124d70b9c218053c426

**Comment by jamesburns** [comment]
Yay!!

-- mobile --
