### ISSUE TITLE
Collection: Creating a collection from an item within a collection, creates a new collection. However if you then open that sub collection from the collection tray, it flash the items and then jumps to the parent collection's items.

### ISSUE THREAD

**Issue by LindseyWagner** [Zeega/Zeega#358]

**Comment by kanarinka** [comment]
I can't replicate this but I'm not sure I'm following the right steps
to reproduce it. Can you list out steps or just show me at Mon
meeting?

On Fri, Feb 3, 2012 at 5:03 PM, Lindsey Wagner
reply@reply.github.com
wrote:

**Comment by lfbrandao** [comment]
Closed from commit by mistake
