### ISSUE TITLE
Collections :: "My Collections" remain the same from playground to playground

### ISSUE THREAD

**Issue by jshapins** [Zeega/Zeega#374]
The items in "Everything" and "My Stuff" are playground-specific, but the collections displayed in the top tray are the same.

**Comment by LindseyWagner** [comment]
James and I spoke about this earlier. Big code change and small use case (only us). To be addressed in next release or future updates.

**Comment by jshapins** [comment]
Y - I marked it as low priority - just wanted to document it for our own
understanding - don't see it as significant at all.

On Wed, Feb 8, 2012 at 11:09 PM, Lindsey Wagner <
reply@reply.github.com
