### ISSUE TITLE
Japanese search queries not working in SOLR

### ISSUE THREAD

**Issue by jshapins** [Zeega/Zeega#417]
福島県 (Fukushima Prefecture)
高台移転 (relocation to high ground)
放射能汚染 (radioactive contamination)
relief
reconstruction
Minami Sanriku
ブログ (blog)
fishing
volunteers
原発 (nuclear plant)

**Comment by kmlawson** [comment]
other examples of search queries:
復興 - reconstruction　(1530 hits for us in website database)
災害 - disaster　(975 hits for us in website database)
台灣 - Taiwan in traditional characters (105 hits for us in website database)

term to check for tweet hits (this is in many tweets):
災害 - disaster

term to check for in testimonial hit:
津波 - tsunami
사람 - person in Korean
大街 - street in Chinese

**Comment by lfbrandao** [comment]
Seems to be fixed - it was a server configuration issue. Can't find testimonials using 사람, but the other queries seem to work. Maybe there's something missing on the data.
