### ISSUE TITLE
JDA- Videos appear to have no date?

### ISSUE THREAD

**Issue by LindseyWagner** [Zeega/Zeega#442]

**Comment by jshapins** [comment]
Just talked to James. This is because the items probably don't have actual dates for media_date_created (I think). Filipe, is it possible to add meaningful data for this? Or do we simply not have it and can't get it?

**Comment by jshapins** [comment]
Sure, I'll get those from the Youtube API (currently they're definitely blank).

**Comment by lfbrandao** [comment]
Fixed
