### ISSUE TITLE
JDA - Homepage: search bar area is funky looking

### ISSUE THREAD

**Issue by LindseyWagner** [Zeega/Zeega#444]
with the "add to archive" button gone, the "in the archive" moved up. It's hard to read on the black and looks like an error. Can we move it back down to where it was and increase the width of the search bar to fit the space better?

**Comment by jshapins** [comment]
How was this done in your wireframes?

**Comment by jshapins** [comment]
Or rather...I agree it's awkward now...can u mock this up?
