### ISSUE TITLE
JDA - Feedback form

### ISSUE THREAD

**Issue by jamesburns** [Zeega/Zeega#447]
Assign EJ.

**Comment by kmlawson** [comment]
One approach:
-use google form, email results to info@jdarchive.org or store in a doc on our google docs for jdarchive.org (google apps)

-email address
-name (optional)
-summary of problem
-URL (autofill from wherever the feedback link was pressed)
-large textbox to allow for more detail.

EJ suggested option of attaching photo? If not too much extra time...

hopefully this can be active close to March 9
