### ISSUE TITLE
JDA - Resize search box to accomodate japanese text

### ISSUE THREAD

**Issue by jamesburns** [Zeega/Zeega#450]

**Comment by kmlawson** [comment]
One or two pixels smaller for the Japanese text should be fine.

**Comment by kanarinka** [comment]
Search box on search page? Can you explain issue a little more - I tried copying and pasting japanese text and it seems to fit into the box.

**Comment by kmlawson** [comment]
the light gray default text on the home page of the search box gets cropped at the top whereas english text fits perfectly.

**Comment by kanarinka** [comment]
818d3930831ad42b60ed368d70c311b59c3c0ca4git
