### ISSUE TITLE
JDA - Update data from Reischauer collection

### ISSUE THREAD

**Issue by jamesburns** [Zeega/Zeega#455]
Websites need their titles, testimonials need metadata

**Comment by kmlawson** [comment]
seeds->title 
(ideally, long descriptions cropped, and tags for the item listed below them if possible?)

**Comment by kmlawson** [comment]
some of the testimonial table data that is useful:
from_year
from_month
from_day
to_year
to_month
to_day
city

and the location of the testimonial which is in 
testimonial_location (where testimonial.id=testimonial_location.testimonial_id)

**Comment by lfbrandao** [comment]
Not everything is supported on the front end yet (i.e. from_year, from_month, etc) but is now included of the database.
