### ISSUE TITLE
JDA - fancybox website view has live link for "View on Internet Archive"

### ISSUE THREAD

**Issue by kmlawson** [Zeega/Zeega#464]
In website fancybox wayback link at top links to earliest archived copy of the page at Internet Archive. However, the "View on Internet Archive" link below the preview of the archived website links to live version.

Recommended change in behavior:
- show live link on top
  -below preview have three links:

Most Recent | Oldest | All

or the like...

To construct the links:
Most recent: http://wayback.archive-it.org/2438/9/[URL]
Oldest: http://wayback.archive-it.org/2438/20110301000000/[URL]
All: http://wayback.archive-it.org/2438/*/[URL]

To know whether a link has been submitted to Internet Archive for archiving or not (if it hasn't, the seed is likely not to be in the archive):

look in the seed database at the global table:

global->name=last_export_stat (gid=3)->value

This "value" gives you the seed ID of the most recently exported (and sent to Internet Archive) seed. Any seed ID>last_export_stat will NOT be in Internet Archive and should probably not be included in the search results.

**Comment by jamesburns** [comment]
Redundant w/ issue #463 – moved comments above to this issue
