### ISSUE TITLE
JDA - testimonials have no paragraph breaks

### ISSUE THREAD

**Issue by kmlawson** [Zeega/Zeega#465]
Testimonials do not display paragraph breaks.

Convert two \r into <p> breaks.

**Comment by lfbrandao** [comment]
Line breaks are being returned from the server but are not being displayed on the front end.

**Comment by kmlawson** [comment]
I see, can these be converted to `<br /><br />` or have paragraph blocks enclosed in `<p>`?

**Comment by kanarinka** [comment]
1fc0e0aa54e99cf86177e6640ac6be93324d2516git

the line breaks seem a little uneven - sometimes there is 1 and sometimes there are 4 - but I've replaced them with <br/> and they are showing now
