### ISSUE TITLE
JDA - Confirm Korean functional for testimonial search

### ISSUE THREAD

**Issue by kmlawson** [Zeega/Zeega#467]
[In this previous issue](https://github.com/Zeega/Zeega-Core/issues/417) it was mentioned that a search for 사람 did not show anything up. Is it possible all Korean search is broken? Or that not all testimonials were imported?

Here are some example testimonials that should be in your database that you can pull text out of to run test searches:

Korean:

http://jdarchive.org/testimonial/public/57/53514320f075?la=ja
http://jdarchive.org/testimonial/public/64/e9a827589370?la=ja
http://jdarchive.org/testimonial/public/60/223f0e6ae15f?la=ja
http://jdarchive.org/testimonial/public/59/65c01b2387a6?la=ja
http://jdarchive.org/testimonial/public/57/53514320f075?la=ja

Chinese example:

http://jdarchive.org/testimonial/public/32/714611f1665a?la=ja

**Comment by lfbrandao** [comment]
Thanks Konrad - I'll check what's happening.

**Comment by lfbrandao** [comment]
Moved to a new repository: https://github.com/Zeega/Japan-Digital-Archive/issues/23
