### ISSUE TITLE
JDA - No quotations for titles in Japanese 

### ISSUE THREAD

**Issue by kmlawson** [Zeega/Zeega#468]
In the Japanese language, it is not common to put " " quotation marks around titles. 

When searching for items in the interface, for example 宮城, note that 

1) both the search results, and 
2) the fancy box

list titles for images and sounds etc. with " " around them. 

Can we do without these quotation marks? Given most assets are in Japanese, probably best to remove them both in English and Japanese interface.

**Comment by jshapins** [comment]
I agree - don't see any need to have quotation marks.
