### ISSUE TITLE
JDA - Searching testimonials for 政府 returns 1 result, shows 2

### ISSUE THREAD

**Issue by kmlawson** [Zeega/Zeega#469]
The two results are identical.

**Comment by lfbrandao** [comment]
@kanarinka the API response seems correct:

http://dev.zeega.org/jdaapisolr/web/api/search?&q=%E6%94%BF%E5%BA%9C&view_type=list&content=text&page=1&r_items=1&r_tags=1&r_itemswithcollections=0

http://dev.zeega.org/march/web/en/search#view_type=list&q=%E6%94%BF%E5%BA%9C&content=text&

Sometimes it shows one result; others shows a duplicate. To reproduce: click on the link above -> change content type to video -> change content type back to Testimonial -> you should see 2 copies of the same testimonial.

**Comment by kanarinka** [comment]
Sorry to blame it on you Filipe! :)
87443af913aebee1b6fc0379176802808feb98e6git
