### ISSUE TITLE
JDA - pasting text into search box hides text

### ISSUE THREAD

**Issue by kmlawson** [Zeega/Zeega#470]
Chrome 17.0.963 OS X - pasting any text into the search box (not on the main home page but on the list or time/space view), like "Japan reconstruction" obscures the pasted text. Pressing enter shows the text again.

**Comment by jshapins** [comment]
This is a duplicate of issue #418. Problem resides with DocumentCloud. Exists on their site, too.

**Comment by jbergen** [comment]
This is a bug with the VisualSearch. Pasted text doesn't always come in with dimensions

-mobilejoseph
