### ISSUE TITLE
JDA - Featured collections not currently loading (i.e. Zeega alpha player) 

### ISSUE THREAD

**Issue by jshapins** [Zeega/Zeega#477]
http://alpha.zeega.org/project/332/view
http://alpha.zeega.org/project/333/view

Is this possibly due to browser detection?

**Comment by jamesburns** [comment]
No idea... That's bizarre, both safari and chrome?

-- mobile --

**Comment by lfbrandao** [comment]
These exist, but don't seem to be finished:
http://alpha.zeega.org/project/322/view
http://alpha.zeega.org/project/323/view

Are these the projects missing?
