### ISSUE TITLE
JDA - Layer buttons left aligned, but layer names right aligned

### ISSUE THREAD

**Issue by kmlawson** [Zeega/Zeega#491]
Map layer tab:

The checkboxes are aligned left, but the names of the layers are aligned right. Looks strange.

bootstrap.css 
@ line 624 

delete text-align:right?

**Comment by kmlawson** [comment]
Another approach: have everything text-align:right but place the checkboxes on the right side.

**Comment by kanarinka** [comment]
ee00049f3f7ff6984e8193656c178eb81ee2d8cc
