### ISSUE TITLE
JDA- Add Google Analytics

### ISSUE THREAD

**Issue by LindseyWagner** [Zeega/Zeega#496]

**Comment by kmlawson** [comment]
Lindsey, I added your and Filipe's gmail to our analytics.google.com account, when you move to alpha.jdarchive can you use that ID number? 

I added you both as admin users so you should be able to add more people if you like.

You should see your access to the analytics for jdarchive if you login with your gmail at analytics.google.com

Tracking ID: UA-22729281-2

```
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-22729281-2']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

```
