### ISSUE TITLE
JDA - Fancy box view of websites showing live website by default

### ISSUE THREAD

**Issue by kmlawson** [Zeega/Zeega#498]
Search for Japan and swtich to web sites:

There is the entry: 
Tzu Chi delivers aid to 1,200 disaster survivors in Japan

When you click on the page, it shows 404 (http://www.us.tzuchi.org/usa/home.nsf/report/k14276), because the default view for a website is the live webpage. However, more and more frequently, pages we archived will be gone from the internet, so recommend we, by default, show the oldest archived version in the view box.

http://wayback.archive-it.org/2438/20110603222612/http://www.us.tzuchi.org/usa/home.nsf/report/k14276

As indicated in separate issue, recommend adding links for "oldest" and "all" versions where there is now "View on Internet Archive"

**Comment by lfbrandao** [comment]
Fixed
