### ISSUE TITLE
JDA - feedback to user while loading map items

### ISSUE THREAD

**Issue by kmlawson** [Zeega/Zeega#499]
Until the performance of the time and space view is significantly better, would it be possible to provide some feedback to the user so they know what is happening?

Currently the geolocated points can take 5-20 seconds to load. Can we have a "loading points" message or some progress indicator etc. show while it is loading points on the map, which disappears when the points are completely loaded?

**Comment by LindseyWagner** [comment]
Add loading icon and message based on timing (e.g. after 3 seconds...)

Kyle noted we have the "loading" language in the translation doc.
