### ISSUE TITLE
When adding a set from flickr from a set page, widget also saves a set thumbnail which is tiny and a duplicate of one of the photos. 

### ISSUE THREAD

**Issue by LindseyWagner** [Zeega/Zeega#512]
http://www.flickr.com/photos/klasojebo/sets/72157619273191448/with/3606577845/
link to original from the thumbnail takes you to the set page

**Comment by lfbrandao** [comment]
Fixed on the backend (606571c02030593eb1f3213879e13656db2d9fb6).
Needs some frontend changes - https://github.com/Zeega/Zeega-Core/issues/526
