### ISSUE TITLE
Unable to delete collections.

### ISSUE THREAD

**Issue by LindseyWagner** [Zeega/Zeega#514]
Will appear as if gone but upon refresh they are still there.

**Comment by kanarinka** [comment]
seems to be on the server side - When the browser makes a delete request like this - http://dev.zeega.org/kanarinka/web/api/collections/13 then it returns:

Fatal error: Call to undefined method Doctrine\ORM\EntityManager::setEnabled() in /var/www/kanarinka/src/Zeega/ApiBundle/Controller/CollectionsController.php on line 315
