### ISSUE TITLE
Change the data field used to preview collections on the lightbox 

### ISSUE THREAD

**Issue by lfbrandao** [Zeega/Zeega#526]
On the browser, click on a collection. The image displayed on the lightbox should be selected as follows:
- if 'uri' is not null, use 'uri'
- if 'uri' is null and thumbnail_url is not null, use 'thumbnail_url'
- else use 'default image'

**Comment by kanarinka** [comment]
just talked with filipe and we are going to remove collections from My Stuff so this is not an issue
