### ISSUE TITLE
Bookmarklet: Added a set that has 337 photos

### ISSUE THREAD

**Issue by LindseyWagner** [Zeega/Zeega#551]
I know we can only grab 100 but I wanted to see how we deal with that on the bookmarklet.
1.  we didn't tell them they're only getting 100. We should specifically say something to the effect that only the first 100 can be grabbed. All others must be added individually?
2. it killed the bookmarklet, nothing is coming up.
3. It killed the application. My collections wouldn't load.

**Comment by LindseyWagner** [comment]
hmm projects aren't loading either. maybe i have to kill browser.

**Comment by LindseyWagner** [comment]
k - so app is back. 

collection has only 10 items. 

can we just do 100 images at a time per set? so like if you went back to the same set, it'd be like add the  next 100 images?

**Comment by lfbrandao** [comment]
Need to check that - I'm limiting to 100 but there's something wrong on the Flickr parser. If you find a large soundcloud set give it a try.
