### ISSUE TITLE
Collections: Need a visual look for collections (stack of photos).

### ISSUE THREAD

**Issue by LindseyWagner** [Zeega/Zeega#552]
Right now looks like you have the same image twice. No way to distinguish and image from another collection?
Or just put the overlay and name over it?

**Comment by kanarinka** [comment]
Not sure I understand this - in the collections browser you see collections at the top in the carousel and items below in "My Stuff" - are you seeing items and collections mixed together somewhere?

**Comment by LindseyWagner** [comment]
Yeah, I think i was incorrect. It's not the collection but the thumbnail of
the set from flickr.  Either way it's confusing. Maybe we can just not show
them since we're not showing any other collections.
Might be better to speak with Felipe.

On Fri, Apr 13, 2012 at 9:02 AM, kanarinka <
reply@reply.github.com

**Comment by kanarinka** [comment]
I see what you are saying. It looks like the Flickr set thumbnail shows up as both an item and a collection and it should just be a collection. 

Filipe - can you make it so that the thumbnail for Flickr sets doesn't show up as an item?

**Comment by lfbrandao** [comment]
Removed collections from the items list.
