### ISSUE TITLE
Editor: Cleaning up buttons

### ISSUE THREAD

**Issue by LindseyWagner** [Zeega/Zeega#560]
Can we add some padding between last scrubber and buttons?
Do the buttons need to be full width? Can they also have some slight padding between each other? Or can they be less white and buttony and more like a list of menu options with lines between them that have a hover and select look?

**Comment by jbergen** [comment]
I've added space between controls for legibility, but we'll need some more design consideration before updating the rest of the look (ie swapping out button styes)
