### ISSUE TITLE
Admin :: creating new site from Sonata generates Symfony error

### ISSUE THREAD

**Issue by jshapins** [Zeega/Zeega#596]
http://alpha.zeega.org/admin/zeega/data/site/create

Please define a type for field `created_at` in `Zeega\AdminBundle\AdminEntity\SiteAdmin`

**Comment by lfbrandao** [comment]
Fixed on alpha. Additionally, I changed the order items are displayed on the Site and User list to show the most recent first (can revert this change if you prefer the old way). Sites should now also be editable. 
Creating users still not possible (not sure if we will be able to do it using this interface).
