### ISSUE TITLE
Bookmarklet: "only importing 100 items of set" message should come before you click add to zeega

### ISSUE THREAD

**Issue by LindseyWagner** [Zeega/Zeega#600]
just doesn't seem like people will notice it at the end of the message after you add. 

should be located near the number in set.

**Comment by lfbrandao** [comment]
Lindey's screenshots:
http://i1048.photobucket.com/albums/s379/luisfbrandao/2.jpg
http://i1048.photobucket.com/albums/s379/luisfbrandao/1.jpg
