### ISSUE TITLE
Collections: Collections as an item

### ISSUE THREAD

**Issue by LindseyWagner** [Zeega/Zeega#601]
It seems that to get rid of the flicker set thumbnail being shown in the collections browser, we've also removed showing collections as an item. 

This isn't too confusing in the "my stuff" area but it posed a challenge when you add a collection to another collection. 

The collection will count it as an item but not show the sub collection in the collection. 

I will send a pic as this is confusing.

**Comment by lfbrandao** [comment]
I can make this work for nested collections, but I'm not sure it makes sense. I would keep collections hidden while we don't have a way of displaying them on the items list.

Lindsey's screenshot: http://i1048.photobucket.com/albums/s379/luisfbrandao/ScreenShot2012-04-20at12459PM.png

**Comment by LindseyWagner** [comment]
i think we should just add a simple visual treatment that makes it look stacked?

it's really wierd to be able to add them but not see them. 

eventually we'll go to seeing them... like we're thinking in jda.
