### ISSUE TITLE
Editor :: filter by media type requires hitting enter on a second dropdown

### ISSUE THREAD

**Issue by jshapins** [Zeega/Zeega#645]
When clicking the filter dropdown, you choose the media type, then "filter:" appears and you have to click enter on a second dropdown to get new results in the item viewer.

**Comment by lfbrandao** [comment]
A different but related issue: http://i1048.photobucket.com/albums/s379/luisfbrandao/ScreenShot2012-04-25at115700AM.png

If you select more than one media type from the dropdown it appends it to the search query but it doesn't actually filter.
