### ISSUE TITLE
Google plus embed - linked to a symfony error

### ISSUE THREAD

**Issue by LindseyWagner** [Zeega/Zeega#646]
Item "cover_image" for "Array" does not exist in ZeegaCoreBundle:Editor:embed.html.twig at line 6
500 Internal Server Error - Twig_Error_Runtime

appears to be because it was a project without a cover image (an older project)

**Comment by lfbrandao** [comment]
To fix on alpha08 update. The database schema changed to solve this problem.

**Comment by lfbrandao** [comment]
Added default cover image to all alpha projects that didn't have a cover image
