### ISSUE TITLE
Editor: What happened to instructions appearing the first time you use the editor?

### ISSUE THREAD

**Issue by LindseyWagner** [Zeega/Zeega#664]
Did we kill that? Seems really helpful for first time users.

**Comment by jbergen** [comment]
we pulled it in 0.6 because apis changed. This task it large enough that it would probably mean no non-linearity for next week. Maybe this is something that Andy can work on?

**Comment by jshapins** [comment]
I think we should shelf this for now and do a thorough UX spec for ideal instructions throughout application
