### ISSUE TITLE
Player :: old alpha project doesn't play

### ISSUE THREAD

**Issue by jshapins** [Zeega/Zeega#669]
http://alpha.zeega.org/project/510/view#player/frame/2949

**Comment by lfbrandao** [comment]
Should be fixed

**Comment by jshapins** [comment]
Seems like there are still some issues. Particularly, seems like first frames have trouble. Here's an example: 

http://alpha.zeega.org/project/189/view#player/frame/926

**Comment by jshapins** [comment]
Also weird flashings. Click back/forth on this one: 

http://alpha.zeega.org/project/174/view#player/frame/982

Could it have something to do w/ transitions data from 0.5 to 0.6?

**Comment by lfbrandao** [comment]
Fixed; some projects may need extra custom changes.
