### ISSUE TITLE
Bookmarklet :: adding a set from Flickr creates a collection but collection has no items

### ISSUE THREAD

**Issue by jshapins** [Zeega/Zeega#688]

**Comment by lfbrandao** [comment]
I didn't fix this one, but it just worked for me for a set - can you send the "horses" set that wasn't working?

**Comment by jshapins** [comment]
Yeah - I closed it because it's working for me now, too. The horses set
says it's already added. It's also working with other sets. If you want to
test a bit w/ sets of all scales, the Boston Public Library is a great
source:

http://www.flickr.com/photos/boston_public_library/collections/

On Tue, May 1, 2012 at 7:48 AM, Luís Filipe Brandão <
reply@reply.github.com

**Comment by lfbrandao** [comment]
Thanks Jesse! It also worked for me for a few sets, but there's still an issue with these sets from the Boston Public Library.
