### ISSUE TITLE
Bug: Login goes to bad player?

### ISSUE THREAD

**Issue by LindseyWagner** [Zeega/Zeega#694]
http://staging.zeega.org/web/login
goes to
http://staging.zeega.org/web/bad/browser

**Comment by LindseyWagner** [comment]
happening on alpha too.

**Comment by jshapins** [comment]
Which browser u using? This is expected behavior for Firefox.

**Comment by LindseyWagner** [comment]
ahh good point. firefox is easier here with connecting to wifi networks but
i forgot i was not in chrome. the url made think some player updates had
done something mysterious.

On Tue, May 1, 2012 at 6:21 AM, Jesse Shapins <
reply@reply.github.com

**Comment by jshapins** [comment]
Haha. Might be worth doing a more rigorous UX on the page people get when they are not using a supported browser.
