### ISSUE TITLE
Bookmarklet :: doesn't properly ingest YouTube tags

### ISSUE THREAD

**Issue by jshapins** [Zeega/Zeega#783]
For this video, tags field has this info:

http://gdata.youtube.com/schemas/2007#video,Games,Tomb Raider,Lara Croft,Trailer,Official,Lara,Croft,Tomb,Raider,Crossroads,E3,2012,Youtube

**Comment by lfbrandao** [comment]
Fixed - I came across this issue yesterday while importing the JDA videos. The fix is on the new API branch that I have been using for JDA and that needs to be merged with alpha.
