### ISSUE TITLE
Color Layer:: Can't update color

### ISSUE THREAD

**Issue by LindseyWagner** [Zeega/Zeega#817]
http://alpha.zeega.org/site/home/project/1129#editor/sequence/1263/frame/6723

appears changed but doesn't save

**Comment by jshapins** [comment]
This is super close! Saving all seems to be working well. But small issue. When I create a color layer, change the color, preview and then come back to the frame, the color layer on the frame is the right color, but the color picker displays the default pink. If I refresh, the proper color is displayed in the picker.
