### ISSUE TITLE
Community :: add templates for about pages

### ISSUE THREAD

**Issue by jshapins** [Zeega/Zeega#878]
Set up so that each page accessible from the about dropdown is a unique URL and can be easily edited independently. No need to have sub-nav on pages nor hashed URLs. Pages include:

Mission
Productions
Engine
Team
Contact
Terms
Privacy

**Comment by kanarinka** [comment]
http://dev.zeega.org/kanarinka/web/community/about
http://dev.zeega.org/kanarinka/web/community/engine
http://dev.zeega.org/kanarinka/web/community/team
http://dev.zeega.org/kanarinka/web/community/contact
http://dev.zeega.org/kanarinka/web/community/productions
http://dev.zeega.org/kanarinka/web/community/privacy
http://dev.zeega.org/kanarinka/web/community/terms

Ported over Jesse's content but mostly left styles alone for you to modify Jesse
